version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: kafka-zookeeper
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka:2.11-1.1.0
    container_name: ${KAFKA_CONTAINER_NAME}
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.178.38
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
    ports:
      - ${KAFKA_PORT_HOST}:${KAFKA_PORT_CONTAINER}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  node-producer:
    build: ./services/producer
    container_name: ${PRODUCER_CONTAINER_NAME}
    ports:
      - ${PRODUCER_PORT_HOST}:${PRODUCER_PORT_CONTAINER}
    depends_on:
      - kafka
    volumes:
      - ./services/producer/:/usr/src/app
    env_file:
      - .env
  node-consumer:
    build: ./services/consumer
    container_name: ${CONSUMER_CONTAINER_NAME}
    ports:
      - ${CONSUMER_PORT_HOST}:${CONSUMER_PORT_CONTAINER}
    depends_on:
      - kafka
    volumes:
      - ./services/consumer/:/usr/src/app
    env_file:
      - .env
