version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: kafka-zookeeper
  kafka:
    image: wurstmeister/kafka:2.11-1.1.0
    container_name: ${KAFKA_CONTAINER_NAME}
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: ${KAFKA_ADVERTISED_HOST_NAME}
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - ${KAFKA_PORT_HOST}:${KAFKA_PORT_CONTAINER}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  node-producer:
    build: ./services/producer
    container_name: ${PRODUCER_CONTAINER_NAME}
    depends_on:
      - kafka
    volumes:
      - ./services/producer/:/usr/src/app
    env_file:
      - .env
  node-consumer:
    build: ./services/consumer
    container_name: ${CONSUMER_CONTAINER_NAME}
    depends_on:
      - kafka
    volumes:
      - ./services/consumer/:/usr/src/app
    env_file:
      - .env
  nginx:
    container_name: nginx
    restart: always
    build:
      context: ./nginx
    ports:
      - ${NGINX_PORT_HOST}:${NGINX_PORT_CONTAINER}
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - node-consumer
      - node-producer
