version: "3"
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    container_name: kafka-zookeeper
    ports:
      - 2181:2181
  kafka:
    image: wurstmeister/kafka:2.11-1.1.0
    container_name: kafka-kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.178.38
      KAFKA_CREATE_TOPICS: test-topic:1:1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - 9095:9092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  node-producer:
    build: ./services/producer
    container_name: ${PRODUCER_CONTAINER_NAME}
    ports:
      - ${PRODUCER_PORT}:${PRODUCER_PORT}
    depends_on:
      - kafka
    volumes:
      - ./services/producer/:/usr/src/app
    env_file:
      - .env
