# PRODUCER
# getting all topics
GET http://localhost:8081/producer/topics/getTopics

####
# checking if a topic exists
GET http://localhost:8081/producer/topics/doesTopicExist 
content-type: application/json

{
    "topic": "mongo-topic"
}

####
# getting topic metadata
GET http://localhost:8081/producer/topics/getTopicMetadata 
content-type: application/json

{
    "topic": "mongo-topic"
}


####
# creating a topic
POST http://localhost:8081/producer/topics/createTopic HTTP/1.1
content-type: application/json

{
    "topic": "mongo-topic"
}

####
# deleting a topic
DELETE http://localhost:8081/producer/topics/deleteTopic HTTP/1.1
content-type: application/json

{
    "topic": "some-non-existent-topic"
}

####
# deleting topics
DELETE http://localhost:8081/producer/topics/deleteTopics HTTP/1.1
content-type: application/json

{
    "topics": ["1" , "3"]
}


####
# sending a message to a topic that does exist
POST http://localhost:8081/producer/message/sendMessage HTTP/1.1
content-type: application/json

{
    "topic": "mongo-topic",
    "message" : {
        "name" : "samy",
        "age" : 234235
    }
}

####
# sending a message to a topic that does not exist
POST http://localhost:8081/producer/message/sendMessage HTTP/1.1
content-type: application/json

{
    "topic": "mongo-topic",
    "message" : "Some Generated Message"
}

####
# sending a number of random messages
POST http://localhost:8081/producer/message/sendRandomMessage HTTP/1.1
content-type: application/json

{
    "topic": "mongo-topic",
    "number" : 300
}

###
# broadcasting a message to all topics provided
POST http://localhost:8081/producer/message/broadcastMessage HTTP/1.1
content-type: application/json

{
    "topics": ["first-topic" , "mongo-topic" ],
    "message" : "Broadcasted message"
}

###



# CONSUMER
# subscribing to a topic that does not exist
POST http://localhost:8081/consumer/topics/subscribe HTTP/1.1
content-type: application/json

{
    "topic": "myTopic"
}

####
# subscribing to a topic that does exist
POST http://localhost:8081/consumer/topics/subscribe HTTP/1.1
content-type: application/json

{
    "topic": "mongo-topic"
}
